Zolko-123/FreeCAD_Assembly4

Mod_Asm4/importDatumCmd.py, Mod_Asm4/insertLinkCmd.py, Mod_Asm4/placeDatumCmd.py, Mod_Asm4/placeLinkCmd.py
=> Misc. source comment typos and whitespace fixes

README.md
* Incorporate correct markdown (remove `<br>`'s
* formatting for improved readability  
* typo fixes
=> README: Mardown formatting + fixes + readability tweaks

README.md
Preview: https://github.com/luzpaz/FreeCAD_Assembly4/blob/README/README.md
=> README: Update + fix markdown + refine

TUTORIAL1.md
=> Tutorial1.md: markdown tweaks

TUTORIAL1.md
Missed this in the previous PR
=> TUTORIAL1.md refinement

TUTORIAL1.md
Minor fix, the subject should tell all you need to know. :-)
=> Fix broken link to bearing stp file

InitGui.py, Resources/icons/Asm4_LinkArray.svg, newLinkArray.py
A link array now can be created from within Assembly 4.
In order to create an array, a App::Link object needs to be selected first. Then a name for the new array can be given in the pop-out dialog. 
Once the array is created, its parameters (like size and type). The wiki contains more information information about link array https://www.freecadweb.org/wiki/Draft_LinkArray
=> Added Link Array

INSTRUCTIONS.md
updated broken links of icons in documentations
=> fix broken icon urls in INSTRUCTIONS.md

Examples/Tutorial1/TUTORIAL1.md
Updated some wording to match the headers of the latest 0.19 pre-release (19274) + Assembly4.  Also removed the trailing spaces on some sentences, for general neatness. :smile:
=> Updating some wording for Tutorial 1

Examples/Tutorial1/TUTORIAL1.md
and merged fixes in web/master to development
=> fixed path for icons in tutorial1

FastenersLib.py, INSTRUCTIONS.md, README.md, TECHMANUAL.md, VariablesLib.py, insertLinkCmd.py, newModelCmd.py, placeDatumCmd.py, placeLinkCmd.py, releaseAttachmentCmd.py
=> Fix various typos

README.md
naaaaaan, there are still many more things to do before caring about such aesthetic things
=> Revert "README: Add LGTM badges"

FastenersLib.py, INSTRUCTIONS.md, InitGui.py, README.md, Resources/icons/Asm4_CoordinateSystem.svg, Resources/icons/Asm4_deleteVariable.svg, VERSION, VariablesLib.py, importDatumCmd.py, insertLinkCmd.py, newDatumCmd.py, newModelCmd.py, newPartCmd.py, placeLinkCmd.py
This version allows to directly import (link) PartDesign::Body objects, without the need to wrap them in App::Part containers. There might be unintended side-effects, please report bugs.
=> version 0.9

MeasureTask.py, Resources/icons/Asm4_Axis.svg, Resources/icons/Asm4_CoordinateSystem.svg, Resources/icons/Asm4_Datum.svg, Resources/icons/Asm4_Hole.svg, Resources/icons/Asm4_Plane.svg, Resources/icons/Asm4_Point.svg, Resources/icons/Asm4_select.svg, Resources/icons/Asm4_valid.svg
and new icons, thanks to OficineRobotica
=> improved measure tool

showHideLcsCmd.py
Move to ViewObject.show()/ViewObject.hide() API instead of changing the Visibility attribute, it's about twice faster that way.
=> Show hide lcs

InitGui.py, configurationEngine.py, libAsm4.py, treeSelectionOverride.py
Hi. This is till work in progress, but the engine works for save and restore (right click context menu).
Checked with different levels of sub-sub-assembly.
Please take a look on the code.
Need the icons again.
Need to add UI to select configuration to restore and get a configuration name from the user to save it.
Will explore how to do it on the tasks panel. Will add the rest of the code when I understand how to do it.
=> Configuration engine

InitGui.py, Resources/icons/Asm4_enableLinkSelection.svg, treeSelectionOverride.py
Adding toolbar button to enable/disable select mode.
Unfortunately it looks like there is no way to update the icon after addition of the command on initialization.
All I could do is add a printout that says if the mode was enabled or disabled.
=> Enable/Disable 3D view Link selection mode

Asm4_Measure.py
This adds the units specified in the preferences dialog to the distance measurement. There are other locations where it can be added, if you like the idea. Don't merge this PR just yet, but let me know what you think about this.
=> render distance measurement using unit preferences

Asm4_Measure.py
Reverts Zolko-123/FreeCAD_Assembly4#129
never make PR against master branch, only development branch
=> Revert "render distance measurement using unit preferences"

FastenersLib.py, README.md, VERSION, placeLinkCmd.py
parent combo-box width corrected width
=> placeFasteners update

FastenersLib.py, InitGui.py, Resources/icons/Asm4_cloneFasteners.svg
This command allows to clone fastener for placing one to hole axes.
Steps:
1. create and place a fastener;
2. select the fastener and hole axes to which the clones of selected fastener should be attached;
3. run command.
Command will create clones of the selected fastener for each selected
hole axis and attach them.
=> 'Asm4_cloneFastenersToAxes' command was added.

FastenersLib.py, libAsm4.py
Fixed incorrect behaviour when selected differend linked objects based
on one part/body from other document.
=> 'Asm4_cloneFastenersToAxes' command was improved.

FastenersDummy.py, FastenersLib.py, InitGui.py
=> added cloneFastenerToAxis to FastenersDummy

placeLinkCmd.py
=> placeLink didn't detect when an LCS was selected in the Parent Assembly

Asm4_Measure.py
=> Asm4Mesaure can now measure the origins of LCS

Asm4_Measure.py, FastenersLib.py, insertLinkCmd.py, makeBomCmd.py, newDatumCmd.py, newModelCmd.py
ref: https://lgtm.com/projects/g/Zolko-123/FreeCAD_Assembly4/?mode=tree&ruleFocus=7900090
=> LGTM: Fix 'Testing equality to None' alerts

Asm4wb_locator.py
=> Added Asm4wb_locator (was asm4wb_locator)

Resources/icons/Asm4_SelectionAll.svg, Resources/icons/Snap_Edge.svg, Resources/icons/Snap_Face.svg, Resources/icons/Snap_Vertex.svg
missing icons for selection filter
=> added missing icons

Asm4_libs.py, README.md, VERSION, placeLinkCmd.py
=> v0.10.2, fix a bug in placeFasteners

Asm4_Measure.py, Asm4_libs.py, FastenersLib.py, placeLinkCmd.py
=> add unit spin box

FastenersLib.py, README.md, VERSION, placeLinkCmd.py
=> reverted Asm4.QUnitSpinBox to QtGui.QDoubleSpinBox

Asm4_objects.py, FastenersLib.py, InfoKeys.py, InitGui.py, README.md, infoPartCmd.py, makeBinderCmd.py, makeBomCmd.py, newAssemblyCmd.py
Found via `codespell -q 3 -S *.ts -L vertexes`
=> Fix various typos, grammar, and whitespace

README.md, VERSION, insertLinkCmd.py, placeLinkCmd.py
Print a warning for parts corrupted by v0.11.5
=> update to v0.11.9

Asm4_libs.py, README.md, VERSION, package.xml
=> development => master

README.md
no new version, only updated ReadMe
=> added link to Part_EditAttachment

FastenersLib.py
=> corrected rootAssembly eror in cone fasteners

FastenersLib.py, InfoKeys.py, infoPartCmd.py, makeBomCmd.py
This is an attempt to add fasteners to the BOM. 
It works, needs test.
=> BOM with Fastners

InfoKeys.py, infoPartCmd.py, makeBomCmd.py
This PR continues fix some issues left from the last work in the BOM
What was done
- The code was formatted a bit, but it is readable now
- It does not add the Model since the Model's parts are already being added in the BOM
- Fixes Add/Remove fields on Part Info Configuration
- Fixes Part Info Reset
=> [WIP] Improve BOM

InfoKeys.py, makeBomCmd.py
Late improvements to the bill of materials maker.
- Adds `PartDesign::Body` objects
- Handles `Part::Feature` objects
- Skips (Asm4) Parts when there are other objects inside 
- Skips the Model file since it adds its parts 
- Skips hidden objects and links
Now BOM is more or less working the way I visualized it. 
However, I still have to check with bigger and deeper designs. 
Good, I am building one, so I will keep testing it.
=> Late improvements to the bill of materials maker.

makeBomCmd.py
It Fixes the greedy walk for some specific cases.
Improves console messages with better information
Present parts in the same order they appear, making it easier to verify if the BOM is right.
Now my designs that were made recently with 0.21 and Asm4 work nicely. And also, the design of @hasecilu that is big, complex but quite right. 
This is a late fix. Sorry for too many PRs @Zolko-123
=> Improve BOM part 3

Asm4_libs.py, Asm4_objects.py
When axis is X or Y on LCS. Match positive direction for remaining axis with Placer.Base positive directions
=> Match positive directions on LCS axis too

Asm4_objects.py, makeArrayCmd.py
Added support for ShowElement to behave similar to ordinary Link Arrays and removed workaround to hide  ShowElement
=> Support for ShowElement in ExpressionArray

HelpCmd.py, INSTRUCTIONS.md, InitGui.py
Also redirected the help menu item to open the instructions on github instead of showing "Lorem ipsum"
=> Some updates to documentation

Asm4_objects.py
Great for mirroring in datum plane
https://forum.freecad.org/viewtopic.php?p=674553
=> ExpressionArray, support for PartDesign::Plane

checkInterference.py
Thanks for your last fix. I think we are converging on a nice tool.
This time I fixed the missing test I removed last time by mistake, that was important. 
I also improved the console messages. It will print all the comparisons (including the replicated ones) since it is easier for the user to find them and to make sure all the checks are being performed. It will also add under the comparison the status if it is clear, colliding, touching, or already processed. 
Also, if there is no interference, it now removes the folder, restores the visibility of the Model, and prints a message saying the model is clear. (maybe a popup would be better in this case?)
=> Improvements of Interference Checks with GUI

infoKeys.py, infoPartCmd.py, makeBomCmd.py
I think this might be my first pull request... 
Let me know if you need additional info.
=> Low hanging fruit bug fixes

TranslateUtils.py, gotoDocumentCmd.py, newAssemblyCmd.py
In the meanwhile I recommend you to delete `Asm4_Translate` and change all Qtranslate to translate.
#254
=> Mark gotoDocument() and newAssembly() for translation

Asm4_libs.py, importDatumCmd.py, mirrorPartCmd_obsolete.py, newAssemblyCmd.py, newDatumCmd.py, newPartCmd.py
Fix https://github.com/FreeCAD/FreeCAD/pull/12714 consequences.
=> Fix AttachExtension::Support property rename

newPartCmd.py
This fixes the issue on 1.1-dev while it improves the code efficiency.
It was tested against 0.21, 1.0 and 1.1.0-dev-R40253
=> Fix newBody origin customization
