- Examples/Tutorial2/TUTORIAL2.md
Dear Zolko,
I fixed a few typos in your tutorial. I hope you approve.
toralf
PS: This is my first ever pull request. :)
> fixed some typos

- InitGui.py
- libAsm4.py
- treeSelectionOverride.py
Override 3D view click to select linked part entry in tree view
instead of selecting the body of the part.
Improves the efficiency of work, the assembly properties are faster accessible.
> Override 3D view click to select linked part entry in tree view

- InitGui.py
- libAsm4.py
- placeLinkCmd.py
- showHideLcsCmd.py
Please see the code.
Icons are still missing.
Currently accessible from context menu (right-click) when a part is selected on assembly level or the whole "Model" entry in the tree.
It's slow when there are many objects, I don't like the API we have today with the getSubObjects and getSubObject(name) functions that slow down everything related to tree entries, including the pre-selection I think.
Maybe will look on the code later when I have time...
> Show/Hide LCS in objects and child objects.

- libAsm4.py
- placeLinkCmd.py
This is targeted at the development branch. If you prefer a pull request targeted at the master branch, you can merge https://github.com/Zolko-123/FreeCAD_Assembly4/pull/137 instead.
This adds SpinBoxes for specifying absolute AttachmentOffset values (translation and rotation) in the "Place Linked Part" dialog.
When opening the dialog, the default values of these SpinBoxes correspond to the original AttachmentOffset of the linked part.
Also, if two LCS were selected in the tree view, those LCS are  now pre-selected as attachment-points in the "Place linked Part" dialog.
Usage:
To Move/attach a linked part in an Assembly4 assembly, you now have two options:
workflow a):
1. Select the App::Link for the linked part
2. Clicking the button "Edit Placement of Part" (Tooltip: "Move/Attach a part …
> placeLinkCmd: Specify absolute AttachmentOffset (translation and rotation) of linked part, LCS preselection

- FastenersLib.py
- libAsm4.py
Fastener-dependet functions were returned back to FasterrsLib.
Function 'placeFastenerToLCS' was renamed to 'placeObjectToLCS'.
Function 'makeExpressionFastener' was removed and replaced by 'makeExpressionDatum'.
> Minor refactorings in Fasteners support.

- FastenersLib.py
- placeLinkCmd.py
To the task dialogs 'FastenersLibs.placeFastenerUI' and 'placeLinkCmd.placeLinkUI'
the ability to select HoleAxes in 3D View has been added.
Steps for Part:
1. choose a part;
2. invoke the operation 'Move / Attach a Part in the assembly';
3. in 3D Viwer, select HoleAxes in the part to be attached,
and in the part to which you want to attach;
the order of selection is not important.
Steps for Fastener:
1. choose a fastener;
2. invoke the 'Edit Placement of a Fastener' operation;
3. in 3D Viwer, select the HoleAxis in the part to attach to.
PS: When invoking an operation in 3D Viwer, the entire assembly is selected,
wait for the selection was canceled and then perform the selection of HoleAxes.
PPS: When clicking on an axis, a part or other element in 3D View can be selected,
it is …
> Changes in the behavior of the object and fastener placement commands.

- AnimationLib.py
This PR contains some improvements to animateVariable/the Animation Dialog.
Initially, the goal was to just fix a "freeze-crash" when accidentally trying to start an animation with unsuitable user defined values (e.g. RangeBegin<RangeEnd and Step<0).
Eventually however, the run*-functions were ported from explicit loops (in reaction to button presses) to a QtTimer-based approach in order to prevent possible delays (and sleep-calls) inside the GUI-loop.
Also, values should now be updatable while the animation is running.
Please note that I based this on "development" and did not squash in order to make it easier to follow the changes.
Just let me know in case you'd prefer otherwise.
Thanks! :-)
> Change animation-step-logic to QtTimer-based actions, rather than handling all calculations in loops.

- AnimationLib.py
Hi Zolko,
here are the first two changes requested after my last PR (#175).
Actually having the variable displayed above the slider made some shortcomings with slider handling more obvious.
I hence decided to give the dialog a small handling-overhaul.
Furthermore, all Variables will now have their associated configuration stored directly in the doc-file (using an additional property; basically as suggested in #161, which should be fixed with this PR.)
Just let me know if you have comments and whatever else might be needed to get this merged. :-)
I'll move ahead with animation-recording as suggested in your last post here:
https://github.com/Zolko-123/FreeCAD_Assembly4/pull/175#issuecomment-792345200=
Cheers!
PS: Again, PR based on development, non-squashed for details.
> Overhaul of Animation Dialog, make animation related configuration-values persistent

- AnimationLib.py
This PR is meant to prevent animation when no valid variable is selected and introduces error handling in case that happens nonetheless.
The Run-button will only be enabled when the user selects a valid variable name in the varList-QComboBox. 
This prevents the button from being available with the initial info-text ('Select Variable (only float)') selected.
The state of the Export-button is now handled in the same manner.
A custom exception is raised in case animateVariable operates on an invalid variable-name anyhow.  
This prevents failures when the variable-name was valid when selected in the combobox, but got removed later by non-monitored means (delete-var-dialog or the properties editor itself).
The user is prompted to select a currently existing variable if needed.
(I'm planning to …
> Prevent animation with invalid variable name

- AnimationExportLib.py
This PR aims to fix video-export problems (file ending up empty) for animations.
VideoWriter will be called with specific fourccs and in case the export results in an empty file, the process will be repeated using another codec.
In case exporting fails with all given codecs, an error-message is written to the console.
Furthermore, avi-, mov- and mkv-containers are added to the list of supported video-files.
This should create valid files across different OSes, as long as any valid codec for the given container is available and listed.
> Fix Video Export for various container formats

- AnimationLib.py
This is a short patch for animating variables of any document, instead of only `App.ActiveDocument`. This is useful for synchronizing values among multiple `Model`s. Seems to work well so far.
> Allow animating variables from different documents

- placeLinkUI.py
Hi @Zolko-123,
If I place a part/link, pick a LCS from the **Parent Part** and forgot to pick a LCS from the **Linked Part**,
I will get the warning: **Problem in Selection**
So I figured It could make sense, to have the first LCS already selected, if there is one.
Especially If I have to insert quite a lot of parts and they usually have only one LCS anyway.
It saved me quite some time, not to click all the time the first and only LCS and close the warning window.
This change does not effect the Move/Attach Function.
Cheers
Semi
> Select the first LCS if there is one

- configurationEngine.py
When saving a configuration, only items either directly under the Assembly container, or items in an App::Part container is saved.
This makes configuration useless if you want to organize your assembly in groups (folders) and subgroups.
This PR aims to add support for groups in Asm4 configuration, so that e.g. all fasteners or all LCSs in an assembly can be organized in groups, and the properties of the items in the group are stored in configurations, but not the groups themselves (I don't know if they should.. perhaps?)
> Save configuration properties from items in groups

- configurationEngine.py
Since ObjectName in most cases is wider than the default column width, you have to stretch the column width manually to see the full object name. When switching through multiple configurations this is slightly annoying. This PR sets the default "Column A" width to 250, so most names will be visible in full.
Before:
After:
> Set width of ObjectName column in new configuration spreadsheets

- insertLinkCmd.py
When assembly4 is used with the 0.19 build 19694 version of FreeCad a part is inserted into a model, one gets an error message.
```
Running the Python command 'Asm4_insertLink' failed:
Traceback (most recent call last):
File "C:\Users\wschi\AppData\Roaming\FreeCAD\Mod\Assembly4\insertLinkCmd.py", line 110, in Activated
self.lookForParts()
File "C:\Users\wschi\AppData\Roaming\FreeCAD\Mod\Assembly4\insertLinkCmd.py", line 179, in lookForParts
docTemporary = doc.Temporary 
'App.Document' object has no attribute 'Temporary'
```
It appears that some versions of FreeCad don't have the doc.Temporary attribute. This pull request guards against this situation.
> Wschildbach fix insert link temporary doc

- makeBomCmd.py
`obj.Document.Name` does not have a Document Name like the others, it messes up with some characters that are converted to _ and cannot be restored. 
This is an example of what was happening
> Fix Document Name for Fastners.

- placeLinkUI.py
Helps alot when the LCS is not visible, or a part have many LCSs and user wants to try some of them from the list to see what matches best
> Select the proper entry in the parent list when a part was clicked during link addition

- Asm4_objects.py
X and Y direction didn't match the origins X and Y when choosing the Z axis of an origin as Axis
> Corrected rotation with Axis from origins

- exportFiles.py
This PR makes the `exportFiles` work again when the user has `anytree`
Console view of freecad as an example. 
This is when we don't have the `anytree`
This is when it is available
Thanks for making a dropdown menu for this. It is really good.
> Fixes exportFiles optional behavior

- InitGui.py
- Resources/icons/Asm4_Interference_Check.svg
- Resources/icons/Asm4_Interference_Cleanup.svg
- checkInterference.py
Hi Zolko, this PR is my initial attempt to add my interference check script to this workbench.
The code should be improved of course, and also the idea can get matured by discussing it here.
In short, this adds 2 toolbar icons to Checks Interferences and also Removes the generated Interference check objects. The icons and the place on the toolbar should be also improved later, I just added them to have something to start the discussion.
The idea is quite simple. The interference check iterates through all objects inside the Model/Assembly and performs a `Part > Common` operation with each part against the others. The resulting object that has a volume equal to zero, does not have parts interfering and is excluded. The objects that have a volume greater than zero are interfering with each …
> Add initial interference checks

- newDatumCmd.py
This is outaded.
~Hi, @Zolko-123 this PR improves the Create Datum process.~
~After creating a new Datum, the selection (selected object) is changed, making the process of creating multiple datums a pain.~
~With this fix, it is possible to create multiple Datums on the same object in series since it preserves the original selection.~
~Here is a video of the process after the fix where the selection returns to the Body after each Datum is created.~
https://github.com/user-attachments/assets/35fa55eb-94fd-40e1-adba-4aeb62055baf
> Creates LCS inside a body if features of the body are selected
